// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
}

func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDInstance) DeepCopyInto(out *GGIDInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GGIDInstance) DeepCopy() *GGIDInstance {
	if in == nil {
		return nil
	}
	out := new(GGIDInstance)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GGIDInstanceList) DeepCopyInto(out *GGIDInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GGIDInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GGIDInstanceList) DeepCopy() *GGIDInstanceList {
	if in == nil {
		return nil
	}
	out := new(GGIDInstanceList)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GGIDInstanceSpec) DeepCopyInto(out *GGIDInstanceSpec) {
	*out = *in
	out.Database = in.Database
	if in.IdPConfig != nil {
		in, out := &in.IdPConfig, &out.IdPConfig
		*out = new(IdPConfig)
		**out = **in
	}
}

func (in *GGIDInstanceSpec) DeepCopy() *GGIDInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(GGIDInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDInstanceStatus) DeepCopyInto(out *GGIDInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GGIDInstanceStatus) DeepCopy() *GGIDInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(GGIDInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDTenant) DeepCopyInto(out *GGIDTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GGIDTenant) DeepCopy() *GGIDTenant {
	if in == nil {
		return nil
	}
	out := new(GGIDTenant)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GGIDTenantList) DeepCopyInto(out *GGIDTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GGIDTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GGIDTenantList) DeepCopy() *GGIDTenantList {
	if in == nil {
		return nil
	}
	out := new(GGIDTenantList)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GGIDTenantSpec) DeepCopyInto(out *GGIDTenantSpec) {
	*out = *in
	if in.IdPConfig != nil {
		in, out := &in.IdPConfig, &out.IdPConfig
		*out = new(IdPConfig)
		**out = **in
	}
}

func (in *GGIDTenantSpec) DeepCopy() *GGIDTenantSpec {
	if in == nil {
		return nil
	}
	out := new(GGIDTenantSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GGIDTenantStatus) DeepCopyInto(out *GGIDTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GGIDTenantStatus) DeepCopy() *GGIDTenantStatus {
	if in == nil {
		return nil
	}
	out := new(GGIDTenantStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *IdPConfig) DeepCopyInto(out *IdPConfig) {
	*out = *in
}

func (in *IdPConfig) DeepCopy() *IdPConfig {
	if in == nil {
		return nil
	}
	out := new(IdPConfig)
	in.DeepCopyInto(out)
	return out
}
