version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec
    - revive
    - misspell

  settings:
    gosec:
      excludes:
        - G104
        - G402
        - G115
        - G401
        - G404
        - G505
        - G107
        - G201
        - G306
      severity: medium
      confidence: medium
    revive:
      severity: warning
    gocritic:
      disabled-checks:
        - dupBranchBody
        - ifElseChain
        - assignOp
        - appendAssign
        - exitAfterDefer
        - offBy1

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
