"use client";
import { useState, useEffect, useCallback } from "react";
import { GitMerge, Plus, X, Clock, Activity } from "lucide-react";
interface CorrelationRule { id: string; rule_name: string; source_event: string; target_event: string; time_window: string; correlation_type: string; action: string; }
interface Incident { id: string; rule_name: string; events_count: number; first_seen: string; last_seen: string; severity: "low" | "medium" | "high" | "critical"; status: "open" | "investigating" | "resolved"; }
const sevColors: Record<string, string> = { low: "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-400", medium: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400", high: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400", critical: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400" };
const statusColors: Record<string, string> = { open: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400", investigating: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400", resolved: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400" };
export default function EventCorrelationPage() {
  const [rules, setRules] = useState<CorrelationRule[]>([]);
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ rule_name: "", source_event: "", target_event: "", time_window: "5m", correlation_type: "temporal", action: "alert" });
  const [selectedIncident, setSelectedIncident] = useState<string | null>(null);
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/audit/event-correlation", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) { const d = await res.json(); setRules(d.rules || []); setIncidents(d.incidents || []); } } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const createRule = async () => { if (!form.rule_name) return; try { await fetch("/api/v1/audit/event-correlation/rules", { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(form) }); setShowCreate(false); setForm({ rule_name: "", source_event: "", target_event: "", time_window: "5m", correlation_type: "temporal", action: "alert" }); fetchData(); } catch { /* noop */ } };
  const openIncidents = incidents.filter((i) => i.status === "open").length;
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><GitMerge className="w-6 h-6 text-purple-500" /> Event Correlation</h1><p className="text-sm text-gray-500 mt-1">Define correlation rules and track correlated incidents.</p></div><button onClick={() => setShowCreate(true)} className="px-4 py-2 rounded-lg bg-purple-600 text-white text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4" /> New Rule</button></div>
      {openIncidents > 0 && <div className="rounded-lg border border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-900/20 p-3 flex items-center gap-2"><Activity className="w-5 h-5 text-red-500" /><span className="font-semibold text-red-700 dark:text-red-400">{openIncidents} open incidents</span></div>}
      <div><h2 className="text-sm font-semibold mb-2">Correlation Rules ({rules.length})</h2><div className="overflow-x-auto rounded-lg border dark:border-gray-800"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-4 py-3 text-left font-medium">Rule</th><th className="px-4 py-3 text-left font-medium">Source</th><th className="px-4 py-3 text-left font-medium">Target</th><th className="px-4 py-3 text-left font-medium">Window</th><th className="px-4 py-3 text-left font-medium">Type</th><th className="px-4 py-3 text-left font-medium">Action</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{rules.map((r) => (<tr key={r.id} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-4 py-3 font-medium">{r.rule_name}</td><td className="px-4 py-3 font-mono text-xs">{r.source_event}</td><td className="px-4 py-3 font-mono text-xs">{r.target_event}</td><td className="px-4 py-3 text-xs">{r.time_window}</td><td className="px-4 py-3"><span className="px-2 py-0.5 rounded text-xs bg-gray-100 dark:bg-gray-800">{r.correlation_type}</span></td><td className="px-4 py-3"><span className="px-2 py-0.5 rounded text-xs bg-blue-100 dark:bg-blue-900/30 dark:text-blue-400">{r.action}</span></td></tr>))}{rules.length === 0 && !loading && <tr><td colSpan={6} className="px-4 py-8 text-center text-gray-500">No rules.</td></tr>}</tbody></table></div></div>
      <div><h2 className="text-sm font-semibold mb-2">Incidents ({incidents.length})</h2><div className="space-y-2">{incidents.map((inc) => (<div key={inc.id} className={"rounded-lg border p-3 cursor-pointer " + (selectedIncident === inc.id ? "border-purple-500" : "dark:border-gray-800")} onClick={() => setSelectedIncident(selectedIncident === inc.id ? null : inc.id)}><div className="flex items-center justify-between"><div><span className="font-medium text-sm">{inc.rule_name}</span><span className="text-xs text-gray-400 ml-2">{inc.events_count} events</span></div><div className="flex items-center gap-2"><span className={"px-2 py-0.5 rounded text-xs " + sevColors[inc.severity]}>{inc.severity}</span><span className={"px-2 py-0.5 rounded text-xs " + statusColors[inc.status]}>{inc.status}</span></div></div><div className="flex items-center gap-3 mt-1 text-xs text-gray-500"><span className="flex items-center gap-1"><Clock className="w-3 h-3" /> First: {inc.first_seen}</span><span>Last: {inc.last_seen}</span></div>{selectedIncident === inc.id && <div className="mt-2 border-t dark:border-gray-800 pt-2"><h4 className="text-xs font-semibold text-gray-500 mb-1">Incident Timeline</h4><div className="space-y-1 text-xs text-gray-500"><div>Event 1: {inc.first_seen} - trigger detected</div><div>Event 2: correlation rule matched</div><div>Event 3: incident created</div></div></div>}</div>))}{incidents.length === 0 && !loading && <p className="text-sm text-gray-500 text-center py-4">No incidents.</p>}</div></div>
      {showCreate && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowCreate(false)}><div className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b dark:border-gray-800"><h3 className="font-semibold">New Correlation Rule</h3><button onClick={() => setShowCreate(false)}><X className="w-5 h-5 text-gray-400" /></button></div><div className="px-6 py-4 space-y-3"><div><label className="text-sm font-medium">Rule Name</label><input type="text" value={form.rule_name} onChange={(e) => setForm({ ...form, rule_name: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Source Event</label><input type="text" value={form.source_event} onChange={(e) => setForm({ ...form, source_event: e.target.value })} placeholder="login.failed" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">Target Event</label><input type="text" value={form.target_event} onChange={(e) => setForm({ ...form, target_event: e.target.value })} placeholder="login.success" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">Time Window</label><input type="text" value={form.time_window} onChange={(e) => setForm({ ...form, time_window: e.target.value })} placeholder="5m" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Correlation Type</label><select value={form.correlation_type} onChange={(e) => setForm({ ...form, correlation_type: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm"><option value="temporal">Temporal</option><option value="causal">Causal</option><option value="pattern">Pattern</option></select></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t dark:border-gray-800"><button onClick={() => setShowCreate(false)} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm">Cancel</button><button onClick={createRule} disabled={!form.rule_name} className="px-4 py-2 rounded-lg bg-purple-600 text-white text-sm font-medium disabled:opacity-50">Create</button></div></div></div>)}
    </div>
  );
}
