// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audit/v1/audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // user | api_key | system | anonymous
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,5,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"` // e.g. "user.login", "role.assign"
	ResourceType  string                 `protobuf:"bytes,7,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,9,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Result        string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"` // success | failure | denied
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,12,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestId     string                 `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditEvent) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditEvent) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorId       *string                `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	Action        *string                `protobuf:"bytes,3,opt,name=action,proto3,oneof" json:"action,omitempty"`
	ResourceType  *string                `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3,oneof" json:"resource_type,omitempty"`
	Result        *string                `protobuf:"bytes,5,opt,name=result,proto3,oneof" json:"result,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	OrderBy       string                 `protobuf:"bytes,8,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // created_at | action | actor_name
	Descending    bool                   `protobuf:"varint,9,opt,name=descending,proto3" json:"descending,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEventsRequest) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *ListEventsRequest) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ListEventsRequest) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *ListEventsRequest) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *ListEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListEventsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListEventsRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_audit_v1_audit_proto protoreflect.FileDescriptor

const file_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x14audit/v1/audit.proto\x12\rggid.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x03\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x05 \x01(\tR\tactorName\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\a \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\t \x01(\tR\fresourceName\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\f \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\x123\n" +
	"\bmetadata\x18\x0e \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf8\x03\n" +
	"\x11ListEventsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1e\n" +
	"\bactor_id\x18\x02 \x01(\tH\x00R\aactorId\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\x03 \x01(\tH\x01R\x06action\x88\x01\x01\x12(\n" +
	"\rresource_type\x18\x04 \x01(\tH\x02R\fresourceType\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x05 \x01(\tH\x03R\x06result\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\aendTime\x88\x01\x01\x12\x19\n" +
	"\border_by\x18\b \x01(\tR\aorderBy\x12\x1e\n" +
	"\n" +
	"descending\x18\t \x01(\bR\n" +
	"descending\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageTokenB\v\n" +
	"\t_actor_idB\t\n" +
	"\a_actionB\x10\n" +
	"\x0e_resource_typeB\t\n" +
	"\a_resultB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"\x85\x01\n" +
	"\x12ListEventsResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.ggid.audit.v1.AuditEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xa8\x01\n" +
	"\fAuditService\x12Q\n" +
	"\n" +
	"ListEvents\x12 .ggid.audit.v1.ListEventsRequest\x1a!.ggid.audit.v1.ListEventsResponse\x12E\n" +
	"\bGetEvent\x12\x1e.ggid.audit.v1.GetEventRequest\x1a\x19.ggid.audit.v1.AuditEventB/Z-github.com/ggid/ggid/api/gen/audit/v1;auditv1b\x06proto3"

var (
	file_audit_v1_audit_proto_rawDescOnce sync.Once
	file_audit_v1_audit_proto_rawDescData []byte
)

func file_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)))
	})
	return file_audit_v1_audit_proto_rawDescData
}

var file_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_audit_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),            // 0: ggid.audit.v1.AuditEvent
	(*ListEventsRequest)(nil),     // 1: ggid.audit.v1.ListEventsRequest
	(*ListEventsResponse)(nil),    // 2: ggid.audit.v1.ListEventsResponse
	(*GetEventRequest)(nil),       // 3: ggid.audit.v1.GetEventRequest
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_audit_v1_audit_proto_depIdxs = []int32{
	4, // 0: ggid.audit.v1.AuditEvent.metadata:type_name -> google.protobuf.Struct
	5, // 1: ggid.audit.v1.AuditEvent.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: ggid.audit.v1.ListEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	5, // 3: ggid.audit.v1.ListEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	0, // 4: ggid.audit.v1.ListEventsResponse.events:type_name -> ggid.audit.v1.AuditEvent
	1, // 5: ggid.audit.v1.AuditService.ListEvents:input_type -> ggid.audit.v1.ListEventsRequest
	3, // 6: ggid.audit.v1.AuditService.GetEvent:input_type -> ggid.audit.v1.GetEventRequest
	2, // 7: ggid.audit.v1.AuditService.ListEvents:output_type -> ggid.audit.v1.ListEventsResponse
	0, // 8: ggid.audit.v1.AuditService.GetEvent:output_type -> ggid.audit.v1.AuditEvent
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_audit_v1_audit_proto_init() }
func file_audit_v1_audit_proto_init() {
	if File_audit_v1_audit_proto != nil {
		return
	}
	file_audit_v1_audit_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_audit_v1_audit_proto = out.File
	file_audit_v1_audit_proto_goTypes = nil
	file_audit_v1_audit_proto_depIdxs = nil
}
