package middleware

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"google.golang.org/grpc/metadata"
)

func TestRequestIDFromContext(t *testing.T) {
	ctx := ContextWithRequestID(context.Background(), "req-123")
	if got := RequestIDFromContext(ctx); got != "req-123" {
		t.Errorf("RequestIDFromContext = %q, want 'req-123'", got)
	}

	// Empty context
	if got := RequestIDFromContext(context.Background()); got != "" {
		t.Errorf("RequestIDFromContext(empty ctx) = %q, want ''", got)
	}
}

func TestPropagateRequestID_FromHeader(t *testing.T) {
	handler := PropagateRequestID(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := RequestIDFromContext(r.Context())
		if id != "client-provided-id" {
			t.Errorf("expected 'client-provided-id', got %q", id)
		}
		w.WriteHeader(200)
	}))

	req := httptest.NewRequest("GET", "/api/v1/data", nil)
	req.Header.Set("X-Request-ID", "client-provided-id")
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	if w.Header().Get("X-Request-ID") != "client-provided-id" {
		t.Errorf("response X-Request-ID = %q", w.Header().Get("X-Request-ID"))
	}
}

func TestPropagateRequestID_AutoGenerated(t *testing.T) {
	handler := PropagateRequestID(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := RequestIDFromContext(r.Context())
		if id == "" {
			t.Error("expected auto-generated request ID in context")
		}
		w.WriteHeader(200)
	}))

	req := httptest.NewRequest("GET", "/api/v1/data", nil)
	// No X-Request-ID header
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	id := w.Header().Get("X-Request-ID")
	if id == "" {
		t.Error("expected auto-generated X-Request-ID in response")
	}
}

func TestRequestIDToOutgoingContext(t *testing.T) {
	ctx := ContextWithRequestID(context.Background(), "grpc-req-id")
	outCtx := RequestIDToOutgoingContext(ctx)

	md, ok := metadata.FromOutgoingContext(outCtx)
	if !ok {
		t.Fatal("expected outgoing metadata to be set")
	}

	vals := md.Get(GRPCRequestIDKey)
	if len(vals) != 1 || vals[0] != "grpc-req-id" {
		t.Errorf("metadata[%s] = %v, want ['grpc-req-id']", GRPCRequestIDKey, vals)
	}
}

func TestRequestIDToOutgoingContext_NoID(t *testing.T) {
	// When context has no request ID, should return context unchanged
	ctx := context.Background()
	outCtx := RequestIDToOutgoingContext(ctx)

	// Should not add any metadata
	md, ok := metadata.FromOutgoingContext(outCtx)
	if ok {
		vals := md.Get(GRPCRequestIDKey)
		if len(vals) > 0 {
			t.Errorf("expected no metadata when no request ID, got %v", vals)
		}
	}
}

func TestRequestIDFromIncomingMetadata(t *testing.T) {
	md := metadata.Pairs(GRPCRequestIDKey, "incoming-req-id")
	id := RequestIDFromIncomingMetadata(md)
	if id != "incoming-req-id" {
		t.Errorf("expected 'incoming-req-id', got %q", id)
	}

	// Empty metadata
	id = RequestIDFromIncomingMetadata(metadata.MD{})
	if id != "" {
		t.Errorf("expected empty string, got %q", id)
	}
}

func TestInjectRequestIDHeader_WithExistingContextID(t *testing.T) {
	ctx := ContextWithRequestID(context.Background(), "ctx-req-id")
	req := httptest.NewRequest("GET", "/downstream", nil)

	InjectRequestIDHeader(ctx, req)

	if req.Header.Get("X-Request-ID") != "ctx-req-id" {
		t.Errorf("expected X-Request-ID to be 'ctx-req-id', got %q", req.Header.Get("X-Request-ID"))
	}
}

func TestInjectRequestIDHeader_WithoutContextID(t *testing.T) {
	req := httptest.NewRequest("GET", "/downstream", nil)

	InjectRequestIDHeader(context.Background(), req)

	id := req.Header.Get("X-Request-ID")
	if id == "" {
		t.Error("expected auto-generated X-Request-ID")
	}
}

func TestInjectRequestIDHeader_DoesNotOverwrite(t *testing.T) {
	ctx := ContextWithRequestID(context.Background(), "ctx-id")
	req := httptest.NewRequest("GET", "/downstream", nil)
	req.Header.Set("X-Request-ID", "already-set")

	InjectRequestIDHeader(ctx, req)

	// Should NOT overwrite an existing header
	if req.Header.Get("X-Request-ID") != "already-set" {
		t.Errorf("expected 'already-set', got %q", req.Header.Get("X-Request-ID"))
	}
}

func TestNewGRPCRequestIDInterceptor(t *testing.T) {
	interceptor := NewGRPCRequestIDInterceptor()
	if interceptor == nil {
		t.Fatal("expected non-nil interceptor")
	}
}

func TestGRPCRequestIDKey_Constant(t *testing.T) {
	if GRPCRequestIDKey != "x-request-id" {
		t.Errorf("GRPCRequestIDKey = %q, want 'x-request-id'", GRPCRequestIDKey)
	}
}

func TestPropagateRequestID_RoundTrip(t *testing.T) {
	var capturedID string
	handler := PropagateRequestID(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedID = RequestIDFromContext(r.Context())

		// Simulate propagating to a downstream HTTP request
		downstreamReq := httptest.NewRequest("GET", "/downstream", nil)
		InjectRequestIDHeader(r.Context(), downstreamReq)

		if downstreamReq.Header.Get("X-Request-ID") != capturedID {
			t.Errorf("downstream X-Request-ID = %q, want %q",
				downstreamReq.Header.Get("X-Request-ID"), capturedID)
		}

		// Simulate propagating to gRPC
		grpcCtx := RequestIDToOutgoingContext(r.Context())
		md, _ := metadata.FromOutgoingContext(grpcCtx)
		if vals := md.Get(GRPCRequestIDKey); len(vals) == 0 || vals[0] != capturedID {
			t.Errorf("gRPC metadata missing request ID")
		}

		w.WriteHeader(200)
	}))

	req := httptest.NewRequest("GET", "/api/v1/data", nil)
	req.Header.Set("X-Request-ID", "round-trip-id")
	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	if capturedID != "round-trip-id" {
		t.Errorf("captured ID = %q, want 'round-trip-id'", capturedID)
	}
}
