package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type Finding struct {
	ID             string `json:"id"`
	Perspective    string `json:"perspective"`
	Category       string `json:"category"`
	Severity       string `json:"severity"`
	File           string `json:"file"`
	Line           int    `json:"line"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Evidence       string `json:"evidence"`
	Recommendation string `json:"recommendation"`
}

type ReviewResult struct {
	Timestamp   string    `json:"timestamp"`
	Perspective string    `json:"perspective"`
	Findings    []Finding `json:"findings"`
	Summary     string    `json:"summary"`
}

// knownFalsePositives is a whitelist of finding IDs that have been reviewed
// and confirmed as false positives or known design choices by the PM.
// These findings will be suppressed in future reports to reduce review noise.
var knownFalsePositives = map[string]bool{
	"rfc-oauth21-1": true, // ResponseTypesSupported only ["code"], not implicit/hybrid
	"rfc-pkce-1":    true, // Only S256 supported, "plain" not in code
	"rfc-oidc-1":    true, // All OIDC discovery fields exist in struct literals
	"rfc-oauth21-2": true, // Password grant kept for backward compatibility (design choice)
	"sec-token-1":   true, // DPoP implemented in dpop_verifier.go, dpop_verify.go, dpop_token_bind.go
	"sec-session-1": true, // IdleTimeout implemented in conf.go:73, hierarchical_session.go:15
}

// dedupFile tracks findings from previous runs to suppress duplicates.
const dedupFile = "/tmp/ggid-auto-review-dedup.json"

func main() {
	perspective := flag.String("perspective", "RFC Standards Compliance", "Review perspective")
	timestamp := flag.String("timestamp", time.Now().Format("2006-01-02 15:04"), "Timestamp")
	flag.Parse()

	result := ReviewResult{
		Timestamp:   *timestamp,
		Perspective: *perspective,
		Findings:    []Finding{},
	}

	repoRoot := "/Volumes/new/ggai/ggid"

	switch *perspective {
	case "RFC Standards Compliance":
		result.Findings = runRFCCompliance(repoRoot)
	case "Security & Migration Analysis":
		result.Findings = runSecurityMigration(repoRoot)
	default:
		result.Findings = runRFCCompliance(repoRoot)
	}

	// Filter out known false positives and previously reported findings.
	result.Findings = filterFindings(result.Findings)

	if len(result.Findings) == 0 {
		result.Summary = fmt.Sprintf("No issues found. Codebase appears clean from the %s perspective.", *perspective)
	} else {
		result.Summary = fmt.Sprintf("Found %d issue(s) from the %s perspective.", len(result.Findings), *perspective)
	}

	output, _ := json.MarshalIndent(result, "", "  ")
	fmt.Println(string(output))

	reportFile := filepath.Join(os.TempDir(), "ggid-auto-review-report.txt")
	if err := os.WriteFile(reportFile, []byte(fmt.Sprintf("%s\n\n%s", string(output), result.Summary)), 0644); err == nil {
		fmt.Printf("\n[Report written to %s]\n", reportFile)
	}

	fmt.Println("\n=== GGID Auto-Review Report ===")
	fmt.Printf("Timestamp: %s\n", result.Timestamp)
	fmt.Printf("Perspective: %s\n", result.Perspective)
	fmt.Printf("Summary: %s\n\n", result.Summary)

	if len(result.Findings) == 0 {
		fmt.Println("No issues found. Codebase appears clean.")
	} else {
		fmt.Printf("Found %d issue(s):\n\n", len(result.Findings))
		for _, f := range result.Findings {
			fmt.Printf("[%s] %s\n", f.Severity, f.Title)
			fmt.Printf("  Category: %s\n", f.Category)
			fmt.Printf("  File: %s", f.File)
			if f.Line > 0 {
				fmt.Printf(":%d", f.Line)
			}
			fmt.Println()
			fmt.Printf("  Description: %s\n", f.Description)
			fmt.Printf("  Evidence: %s\n", truncate(f.Evidence, 200))
			fmt.Printf("  Recommendation: %s\n\n", f.Recommendation)
		}
	}

	fmt.Println("---")
	fmt.Println("This report was generated by the automated 30-minute code review system.")
	fmt.Println("Please review and confirm any defects. Confirmed defects will be assigned to a teammate for fixing.")
}

// filterFindings removes known false positives and previously reported findings
// to reduce review noise. Previously reported findings are tracked in a dedup file.
func filterFindings(findings []Finding) []Finding {
	var filtered []Finding
	for _, f := range findings {
		// Skip known false positives (PM-confirmed)
		if knownFalsePositives[f.ID] {
			continue
		}
		// Skip findings that have been reported in a previous run
		if wasPreviouslyReported(f.ID) {
			continue
		}
		filtered = append(filtered, f)
	}
	// Record current findings for future dedup
	recordFindings(filtered)
	return filtered
}

// wasPreviouslyReported checks if a finding ID was reported in a previous run.
func wasPreviouslyReported(id string) bool {
	data, err := os.ReadFile(dedupFile)
	if err != nil {
		return false
	}
	var prev map[string]string
	if err := json.Unmarshal(data, &prev); err != nil {
		return false
	}
	_, exists := prev[id]
	return exists
}

// recordFindings saves current finding IDs to the dedup file.
func recordFindings(findings []Finding) {
	prev := make(map[string]string)
	if data, err := os.ReadFile(dedupFile); err == nil {
		json.Unmarshal(data, &prev)
	}
	for _, f := range findings {
		prev[f.ID] = f.Title
	}
	data, _ := json.MarshalIndent(prev, "", "  ")
	os.WriteFile(dedupFile, data, 0644)
}

func runRFCCompliance(repoRoot string) []Finding {
	var findings []Finding
	findings = append(findings, reviewOAuth21(repoRoot)...)
	findings = append(findings, reviewPKCE(repoRoot)...)
	findings = append(findings, reviewOIDC(repoRoot)...)
	findings = append(findings, reviewJWT(repoRoot)...)
	findings = append(findings, reviewWebAuthn(repoRoot)...)
	findings = append(findings, reviewSCIM(repoRoot)...)
	return findings
}

func runSecurityMigration(repoRoot string) []Finding {
	var findings []Finding
	findings = append(findings, reviewTokenSecurity(repoRoot)...)
	findings = append(findings, reviewPasswordSecurity(repoRoot)...)
	findings = append(findings, reviewSessionSecurity(repoRoot)...)
	findings = append(findings, reviewAuthFlowSecurity(repoRoot)...)
	findings = append(findings, reviewMigrationGaps(repoRoot)...)
	return findings
}

func reviewOAuth21(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/oauth/internal/service/oauth_service.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if strings.Contains(text, `"token"`) || strings.Contains(text, `"id_token"`) {
			lines := strings.Split(text, "\n")
			for i, line := range lines {
				if strings.Contains(line, `"token"`) || strings.Contains(line, `"id_token"`) {
					findings = append(findings, Finding{
						ID: "rfc-oauth21-1", Perspective: "RFC Standards Compliance",
						Category: "OAuth 2.1", Severity: "High",
						File: "services/oauth/internal/service/oauth_service.go", Line: i + 1,
						Title: "Implicit/hybrid flow response types may violate OAuth 2.1",
						Description: "OAuth 2.1 disallows the implicit flow (response_type=token). If 'token' or 'id_token' response types are advertised or accepted, clients may attempt flows that are insecure by design.",
						Evidence: strings.TrimSpace(line),
						Recommendation: "Remove 'token' and 'id_token' from ResponseTypesSupported. Only advertise 'code'.",
					})
					break
				}
			}
		}
		if strings.Contains(text, `"password"`) && strings.Contains(text, "GrantTypesSupported") {
			findings = append(findings, Finding{
				ID: "rfc-oauth21-2", Perspective: "RFC Standards Compliance",
				Category: "OAuth 2.1", Severity: "Medium",
				File: "services/oauth/internal/service/oauth_service.go", Line: 0,
				Title: "Password grant type advertised in discovery",
				Description: "OAuth 2.1 removes the password grant type (RFC 6749 §4.3). While still present for backward compatibility, advertising it encourages insecure patterns.",
				Evidence: "GrantTypesSupported includes 'password'",
				Recommendation: "Consider deprecating the password grant. If kept for migration, document it as legacy and recommend authorization code + PKCE.",
			})
		}
	}
	return findings
}

func reviewPKCE(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/oauth/internal/domain/models.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if strings.Contains(text, `"plain"`) {
			lines := strings.Split(text, "\n")
			for i, line := range lines {
				if strings.Contains(line, `"plain"`) {
					findings = append(findings, Finding{
						ID: "rfc-pkce-1", Perspective: "RFC Standards Compliance",
						Category: "PKCE (RFC 7636)", Severity: "Low",
						File: "services/oauth/internal/domain/models.go", Line: i + 1,
						Title: "PKCE 'plain' method still supported",
						Description: "RFC 7636 §4.2 states that the 'plain' method is vulnerable to attacks if the code challenge is leaked. OAuth 2.1 mandates S256 only.",
						Evidence: strings.TrimSpace(line),
						Recommendation: "Deprecate 'plain' method. Only accept S256 for new clients.",
					})
					break
				}
			}
		}
	}
	return findings
}

func reviewOIDC(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/oauth/internal/service/oauth_service.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		required := []string{"authorization_endpoint", "userinfo_endpoint", "revocation_endpoint",
			"introspection_endpoint", "response_types_supported", "grant_types_supported",
			"token_endpoint_auth_methods_supported", "code_challenge_methods_supported",
			"scopes_supported", "claims_supported", "id_token_signing_alg_values_supported",
			"subject_types_supported"}
		missing := []string{}
		for _, f := range required {
			if !strings.Contains(text, f) {
				missing = append(missing, f)
			}
		}
		if len(missing) > 0 {
			findings = append(findings, Finding{
				ID: "rfc-oidc-1", Perspective: "RFC Standards Compliance",
				Category: "OIDC Discovery (RFC 8414)", Severity: "Medium",
				File: "services/oauth/internal/service/oauth_service.go", Line: 0,
				Title: "OIDC discovery document missing required fields",
				Description: fmt.Sprintf("The OIDC discovery document is missing required fields per OIDC Core §3: %s", strings.Join(missing, ", ")),
				Evidence: fmt.Sprintf("Missing: %s", strings.Join(missing, ", ")),
				Recommendation: "Add all missing fields to the discovery document to ensure OIDC compliance.",
			})
		}
	}
	return findings
}

func reviewJWT(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/oauth/internal/service/oauth_service.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if !strings.Contains(text, "jti") && !strings.Contains(text, "JTI") {
			findings = append(findings, Finding{
				ID: "rfc-jwt-1", Perspective: "RFC Standards Compliance",
				Category: "JWT (RFC 7519)", Severity: "Medium",
				File: "services/oauth/internal/service/oauth_service.go", Line: 0,
				Title: "JWT 'jti' (JWT ID) claim may be missing from access tokens",
				Description: "RFC 7519 §4.1.7 defines the 'jti' claim for unique token identification. Needed for revocation and replay protection.",
				Evidence: "No 'jti' claim found in access token issuance",
				Recommendation: "Include a unique 'jti' claim in all issued JWTs for revocation and replay detection.",
			})
		}
	}
	return findings
}

func reviewWebAuthn(repoRoot string) []Finding {
	var findings []Finding
	wd := filepath.Join(repoRoot, "services/auth/internal/webauthn")
	if files, err := os.ReadDir(wd); err == nil {
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".go") {
				fp := filepath.Join(wd, f.Name())
				if content, err := os.ReadFile(fp); err == nil {
					text := string(content)
					if strings.Contains(text, "UserVerification") && !strings.Contains(text, "required") {
						findings = append(findings, Finding{
							ID: "rfc-webauthn-1", Perspective: "RFC Standards Compliance",
							Category: "WebAuthn (W3C)", Severity: "Medium",
							File: filepath.Join("services/auth/internal/webauthn", f.Name()), Line: 0,
							Title: "User Verification may not be set to 'required'",
							Description: "WebAuthn Level 3 recommends setting userVerification to 'required' for passwordless authentication.",
							Evidence: "UserVerification found but not set to 'required'",
							Recommendation: "Set userVerification to 'required' in WebAuthn assertion options.",
						})
					}
				}
			}
		}
	}
	return findings
}

func reviewSCIM(repoRoot string) []Finding {
	var findings []Finding
	sd := filepath.Join(repoRoot, "services/identity/internal/scim")
	if _, err := os.Stat(sd); os.IsNotExist(err) {
		findings = append(findings, Finding{
			ID: "rfc-scim-1", Perspective: "RFC Standards Compliance",
			Category: "SCIM 2.0 (RFC 7643/7644)", Severity: "Low",
			File: "services/identity/internal/scim/", Line: 0,
			Title: "SCIM implementation directory not found",
			Description: "The identity service references SCIM but the SCIM implementation directory does not exist.",
			Evidence: "Directory services/identity/internal/scim/ does not exist",
			Recommendation: "Verify SCIM 2.0 implementation exists and covers RFC 7643 (core schema) and RFC 7644 (protocol).",
		})
	}
	return findings
}

func reviewTokenSecurity(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/oauth/internal/service/oauth_service.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if !strings.Contains(text, "token_binding") && !strings.Contains(text, "dpop") {
			findings = append(findings, Finding{
				ID: "sec-token-1", Perspective: "Security & Migration Analysis",
				Category: "Token Security", Severity: "Medium",
				File: "services/oauth/internal/service/oauth_service.go", Line: 0,
				Title: "No DPoP or token binding support",
				Description: "Competitors like Keycloak and Auth0 support DPoP and token binding to prevent token replay.",
				Evidence: "No DPoP or token binding found in token issuance",
				Recommendation: "Implement DPoP (RFC 9449) or token binding (RFC 8473) for access tokens to prevent replay attacks.",
			})
		}
	}
	return findings
}

func reviewPasswordSecurity(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/auth/internal/domain/password_policy.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if !strings.Contains(text, "MaxLength") {
			findings = append(findings, Finding{
				ID: "sec-pw-1", Perspective: "Security & Migration Analysis",
				Category: "Password Security", Severity: "Low",
				File: "services/auth/internal/domain/password_policy.go", Line: 0,
				Title: "No maximum password length enforced",
				Description: "NIST 800-63B recommends a maximum password length of 64 characters to prevent DoS.",
				Evidence: "No MaxLength field in PasswordPolicy",
				Recommendation: "Add a MaxLength field (default 64) and reject passwords longer than this.",
			})
		}
	}
	return findings
}

func reviewSessionSecurity(repoRoot string) []Finding {
	var findings []Finding
	p := filepath.Join(repoRoot, "services/auth/internal/domain/session.go")
	if content, err := os.ReadFile(p); err == nil {
		text := string(content)
		if !strings.Contains(text, "IdleTimeout") && !strings.Contains(text, "idle_timeout") {
			findings = append(findings, Finding{
				ID: "sec-session-1", Perspective: "Security & Migration Analysis",
				Category: "Session Security", Severity: "Medium",
				File: "services/auth/internal/domain/session.go", Line: 0,
				Title: "Idle session timeout may be missing",
				Description: "NIST 800-63B recommends idle session timeouts.",
				Evidence: "No idle timeout field found in Session struct",
				Recommendation: "Add idle timeout tracking to sessions and enforce automatic logout after inactivity.",
			})
		}
		if !strings.Contains(text, "ConcurrentLimit") && !strings.Contains(text, "max_sessions") {
			findings = append(findings, Finding{
				ID: "sec-session-2", Perspective: "Security & Migration Analysis",
				Category: "Session Security", Severity: "Low",
				File: "services/auth/internal/domain/session.go", Line: 0,
				Title: "Concurrent session limit may be missing",
				Description: "Competitors like Okta and Keycloak allow configuring maximum concurrent sessions per user.",
				Evidence: "No concurrent session limit found in Session struct",
				Recommendation: "Add configurable concurrent session limits per user/tenant.",
			})
		}
	}
	return findings
}

func reviewAuthFlowSecurity(repoRoot string) []Finding {
	var findings []Finding
	ad := filepath.Join(repoRoot, "services/auth/internal")
	if files, err := os.ReadDir(ad); err == nil {
		authMethods := 0
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".go") && strings.Contains(strings.ToLower(f.Name()), "mfa") {
				authMethods++
			}
		}
		if authMethods < 2 {
			findings = append(findings, Finding{
				ID: "sec-auth-1", Perspective: "Security & Migration Analysis",
				Category: "Authentication Flow", Severity: "Low",
				File: "services/auth/internal/", Line: 0,
				Title: "Limited MFA method diversity",
				Description: "Competitors like Keycloak and Okta support multiple MFA methods (TOTP, SMS, WebAuthn, Email, Push).",
				Evidence: fmt.Sprintf("Only %d MFA method files found", authMethods),
				Recommendation: "Add additional MFA methods (WebAuthn, SMS, Email) for broader compatibility.",
			})
		}
	}
	return findings
}

func reviewMigrationGaps(repoRoot string) []Finding {
	var findings []Finding
	gaps := []string{
		"Authorization Services", "User Storage SPI", "Identity Brokering",
		"Admin CLI", "Theme system", "Event listener SPI",
		"Rules and Actions", "Hooks", "Universal Login",
		"Anomaly detection", "Attack protection", "Custom database connections",
		"Universal Directory", "SCIM provisioning", "Adaptive MFA",
		"ThreatInsight", "Inline hooks", "API Access Management",
		"Flow engine", "Application provider model", "Source-based user federation",
		"Policy binding system", "Outpost",
	}
	missing := []string{}
	for _, gap := range gaps {
		term := strings.ToLower(strings.ReplaceAll(gap, " ", "_"))
		if !searchRecursive(repoRoot, term) {
			missing = append(missing, gap)
		}
	}
	if len(missing) > 0 {
		findings = append(findings, Finding{
			ID: "mig-1", Perspective: "Security & Migration Analysis",
			Category: "Migration Gap Analysis", Severity: "Low",
			File: "N/A", Line: 0,
			Title: fmt.Sprintf("Missing features compared to Keycloak/Auth0/Okta/Authentik (%d gaps)", len(missing)),
			Description: fmt.Sprintf("The following features are present in major competitors but may be missing or incomplete in GGID: %s", strings.Join(missing, "; ")),
			Evidence: fmt.Sprintf("Missing: %s", strings.Join(missing, "; ")),
			Recommendation: "Prioritize implementing high-value gaps based on migration use cases. Focus on SCIM provisioning, adaptive MFA, and policy-based access.",
		})
	}
	return findings
}

func searchRecursive(root, term string) bool {
	found := false
	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			base := info.Name()
			if base == "vendor" || base == ".git" || base == "node_modules" || base == "test-results" || base == "tests" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, ".ts") && !strings.HasSuffix(path, ".tsx") {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		if strings.Contains(strings.ToLower(string(content)), term) {
			found = true
			return filepath.SkipAll
		}
		return nil
	})
	return found
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
