"use client";
import { useState, useCallback } from "react";
import { FileText, Clock, Check, X } from "lucide-react";
interface Request { id: string; target_role: string; justification: string; duration_days: number; approver: string; status: "pending" | "approved" | "rejected" | "expired"; submitted_at: string; expires_at: string; days_remaining: number; comments: { author: string; text: string; timestamp: string }[]; }
export default function AccessRequestPage() {
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ target_role: "", justification: "", duration_days: 7, approver: "" });
  const [myRequests, setMyRequests] = useState<Request[]>([]);
  const [approvalQueue, setApprovalQueue] = useState<Request[]>([]);
  const [tab, setTab] = useState("my_requests");
  const submitRequest = async () => {
    if (!form.target_role) return;
    try { await fetch("/api/v1/policy/access-request", { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(form) }); setShowForm(false); setForm({ target_role: "", justification: "", duration_days: 7, approver: "" }); }
    catch { /* noop */ }
  };
  const decide = async (id: string, decision: string) => { try { await fetch("/api/v1/policy/access-request/" + id, { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify({ decision }) }); } catch { /* noop */ } };
  const list = tab === "my_requests" ? myRequests : approvalQueue;
  const statusColors: Record<string, string> = { pending: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400", approved: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400", rejected: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400", expired: "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-400" };
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><FileText className="w-6 h-6 text-blue-500" /> Access Request</h1><p className="text-sm text-gray-500 mt-1">Request and approve time-limited role access.</p></div><button onClick={() => setShowForm(true)} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium">New Request</button></div>
      <div className="flex gap-2"><button onClick={() => setTab("my_requests")} className={"px-4 py-2 rounded-lg text-sm font-medium " + (tab === "my_requests" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>My Requests</button><button onClick={() => setTab("approvals")} className={"px-4 py-2 rounded-lg text-sm font-medium " + (tab === "approvals" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>Approval Queue {approvalQueue.length > 0 && "(" + approvalQueue.length + ")"}</button></div>
      {showForm && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowForm(false)}><div className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}><div className="px-6 py-4 border-b dark:border-gray-800"><h3 className="font-semibold">New Access Request</h3></div><div className="px-6 py-4 space-y-3"><div><label className="text-sm font-medium">Target Role</label><input type="text" value={form.target_role} onChange={(e) => setForm({ ...form, target_role: e.target.value })} placeholder="role:admin" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">Justification</label><textarea value={form.justification} onChange={(e) => setForm({ ...form, justification: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Duration (days)</label><input type="number" min={1} value={form.duration_days} onChange={(e) => setForm({ ...form, duration_days: parseInt(e.target.value) })} className="w-20 mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Approver</label><input type="text" value={form.approver} onChange={(e) => setForm({ ...form, approver: e.target.value })} placeholder="manager@example.com" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t dark:border-gray-800"><button onClick={() => setShowForm(false)} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm">Cancel</button><button onClick={submitRequest} disabled={!form.target_role} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium disabled:opacity-50">Submit</button></div></div></div>)}
      <div className="space-y-2">{list.map((r) => (<div key={r.id} className="rounded-lg border dark:border-gray-800 p-3"><div className="flex items-center justify-between"><div><span className="font-medium text-sm">{r.target_role}</span><p className="text-xs text-gray-400">{r.submitted_at} - approver: {r.approver}</p></div><div className="flex items-center gap-2"><span className={"px-2 py-0.5 rounded text-xs " + statusColors[r.status]}>{r.status}</span>{r.status === "pending" && r.days_remaining <= 3 && <span className="flex items-center gap-1 text-xs text-orange-600"><Clock className="w-3 h-3" />{r.days_remaining}d</span>}</div></div><p className="text-sm text-gray-500 mt-1">{r.justification}</p>{r.comments.length > 0 && (<div className="mt-2 space-y-0.5">{r.comments.map((c, i) => (<div key={i} className="text-xs text-gray-400"><span className="font-medium">{c.author}:</span> {c.text}</div>))}</div>)}{tab === "approvals" && r.status === "pending" && <div className="flex gap-2 mt-2"><button onClick={() => decide(r.id, "approved")} className="px-3 py-1 rounded text-xs bg-green-600 text-white flex items-center gap-1"><Check className="w-3 h-3" /> Approve</button><button onClick={() => decide(r.id, "rejected")} className="px-3 py-1 rounded text-xs bg-red-600 text-white flex items-center gap-1"><X className="w-3 h-3" /> Reject</button></div>}</div>))}{list.length === 0 && <p className="text-sm text-gray-500 text-center py-8">No requests.</p>}</div>
    </div>
  );
}
