"use client";
import { useState, useEffect, useCallback } from "react";
import { Flag, Plus, X, ToggleLeft, ToggleRight } from "lucide-react";
import { useTranslations } from "@/lib/i18n";
interface FeatureFlag { name: string; enabled: boolean; rollout_pct: number; target_audience: string; env_override: Record<string, boolean>; }
interface AuditEntry { flag_name: string; action: string; timestamp: string; actor: string; }
const envs = ["dev", "staging", "prod"];
export default function FeatureFlagsPage() {
  const [flags, setFlags] = useState<FeatureFlag[]>([]);
  const [audit, setAudit] = useState<AuditEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: "", target_audience: "all" });
  const t = useTranslations();
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/admin/feature-flags", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) { const d = await res.json(); setFlags(d.flags || d || []); setAudit(d.audit || []); } } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const toggle = async (name: string) => { setFlags(flags.map((f) => f.name === name ? { ...f, enabled: !f.enabled } : f)); try { await fetch("/api/v1/admin/feature-flags/" + name + "/toggle", { method: "POST", headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); fetchData(); } catch { /* noop */ } };
  const create = async () => { if (!form.name) return; try { await fetch("/api/v1/admin/feature-flags", { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify({ name: form.name, enabled: false, rollout_pct: 0, target_audience: form.target_audience, env_override: {} }) }); setShowCreate(false); setForm({ name: "", target_audience: "all" }); fetchData(); } catch { /* noop */ } };
  const toggleEnv = (flagName: string, env: string) => { setFlags(flags.map((f) => { if (f.name === flagName) return { ...f, env_override: { ...f.env_override, [env]: !f.env_override[env] } }; return f; })); };
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Flag className="w-6 h-6 text-blue-500" /> Feature Flags</h1><p className="text-sm text-gray-500 mt-1">{t("featureFlags.subtitle")}</p></div><button onClick={() => setShowCreate(true)} aria-label={t("featureFlags.createFlag")} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4" /> Create Flag</button></div>
      <div className="overflow-x-auto rounded-lg border dark:border-gray-800"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-4 py-3 text-left font-medium">{t("featureFlags.name")}</th><th className="px-4 py-3 text-left font-medium">{t("featureFlags.status")}</th><th className="px-4 py-3 text-left font-medium">{t("featureFlags.rollout")}</th><th className="px-4 py-3 text-left font-medium">{t("featureFlags.audience")}</th>{envs.map((e) => <th key={e} className="px-4 py-3 text-left font-medium capitalize">{e}</th>)}</tr></thead><tbody className="divide-y dark:divide-gray-800">{flags.map((f) => (<tr key={f.name} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-4 py-3 font-mono text-xs font-medium">{f.name}</td><td className="px-4 py-3"><button onClick={() => toggle(f.name)} className="flex items-center gap-1">{f.enabled ? <ToggleRight className="w-6 h-6 text-green-500" /> : <ToggleLeft className="w-6 h-6 text-gray-400" />}<span className={"text-xs " + (f.enabled ? "text-green-600" : "text-gray-400")}>{f.enabled ? t("featureFlags.on") : t("featureFlags.off")}</span></button></td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="w-16 bg-gray-100 dark:bg-gray-800 rounded-full h-2 overflow-hidden"><div className="h-full bg-blue-500 rounded-full" style={{ width: f.rollout_pct + "%" }} /></div><span className="text-xs font-bold">{f.rollout_pct}%</span></div></td><td className="px-4 py-3 text-xs text-gray-500">{f.target_audience}</td>{envs.map((e) => <td key={e} className="px-4 py-3"><input aria-label="Toggle" type="checkbox" checked={f.env_override[e] !== undefined ? f.env_override[e] : f.enabled} onChange={() => toggleEnv(f.name, e)} className="rounded" /></td>)}</tr>))}{flags.length === 0 && !loading && <tr><td colSpan={8} className="px-4 py-8 text-center text-gray-500">{t("featureFlags.noFlags")}</td></tr>}</tbody></table></div>
      {audit.length > 0 && <div className="rounded-lg border dark:border-gray-800 p-4"><h3 className="text-sm font-semibold mb-2">{t("featureFlags.auditLog")}</h3><div className="space-y-1 max-h-32 overflow-y-auto">{audit.map((a, i) => (<div key={i} className="text-xs flex items-center gap-2"><span className="font-mono text-gray-400">{a.timestamp}</span><span className="font-medium">{a.actor}</span><span className="text-gray-500">{a.action}</span><span className="text-blue-600 font-mono">{a.flag_name}</span></div>))}</div></div>}
      {showCreate && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowCreate(false)}><div role="dialog" aria-modal="true" className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b dark:border-gray-800"><h3 className="font-semibold">{t("featureFlags.createFlagTitle")}</h3><button onClick={() => setShowCreate(false)} aria-label="Close"><X className="w-5 h-5 text-gray-400" /></button></div><div className="px-6 py-4 space-y-3"><div><label className="text-sm font-medium">{t("featureFlags.name")}</label><input type="text" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="new_feature_x" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">{t("featureFlags.targetAudience")}</label><input type="text" value={form.target_audience} onChange={(e) => setForm({ ...form, target_audience: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t dark:border-gray-800"><button onClick={() => setShowCreate(false)} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm">{t("featureFlags.cancel")}</button><button onClick={create} disabled={!form.name} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium disabled:opacity-50" aria-label="Action">{t("featureFlags.create")}</button></div></div></div>)}
    </div>
  );
}
