"use client";
import { useState, useEffect, useCallback } from "react";
import { Lock, Save, Shield } from "lucide-react";
import { useTranslations } from "@/lib/i18n";
interface LockoutConfig { max_failed_attempts: number; lockout_duration_minutes: number; progressive_backoff: boolean; captcha_trigger_attempts: number; auto_unlock_minutes: number; per_endpoint: { endpoint: string; max_attempts: number; duration_minutes: number }[]; ip_allowlist: string[]; }
interface ActiveLockout { username: string; ip: string; locked_at: string; unlock_at: string; }
interface LockoutData { config: LockoutConfig; active_lockouts: ActiveLockout[]; }
export default function LockoutPolicyPage() {
  const t = useTranslations();
  const [data, setData] = useState<LockoutData | null>(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/auth/lockout-policy", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) setData(await res.json()); } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const save = async () => { if (!data) return; setSaving(true); try { await fetch("/api/v1/auth/lockout-policy", { method: "PUT", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(data.config) }); } catch { /* noop */ } finally { setSaving(false); } };
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Lock className="w-6 h-6 text-red-500" /> {t("lockoutPolicy.title")}</h1><p className="text-sm text-gray-500 mt-1">{t("lockoutPolicy.subtitle")}</p></div><button onClick={save} disabled={saving || !data} aria-label="Save lockout policy" className="px-4 py-2 rounded-lg bg-red-600 text-white text-sm font-medium flex items-center gap-2"><Save className="w-4 h-4" /> {saving ? t("corsSettings.saving") : t("common.save")}</button></div>
      {data && (<>
        <div className="rounded-lg border dark:border-gray-800 p-4 space-y-4 max-w-lg"><div><label className="text-sm font-medium">{t("lockoutPolicy.maxFailed")}</label><div className="flex items-center gap-3 mt-1"><input aria-label="Data" type="range" min={3} max={20} value={data.config.max_failed_attempts} onChange={(e) => setData({ ...data, config: { ...data.config, max_failed_attempts: parseInt(e.target.value) } })} className="flex-1" /><span className="text-lg font-bold w-8">{data.config.max_failed_attempts}</span></div></div><div className="grid grid-cols-2 gap-3"><div><label className="text-sm font-medium">{t("lockoutPolicy.lockoutDuration")}</label><input type="number" value={data.config.lockout_duration_minutes} onChange={(e) => setData({ ...data, config: { ...data.config, lockout_duration_minutes: parseInt(e.target.value) || 0 } })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm" /></div><div><label className="text-sm font-medium">{t("lockoutPolicy.autoUnlock")}</label><input type="number" value={data.config.auto_unlock_minutes} onChange={(e) => setData({ ...data, config: { ...data.config, auto_unlock_minutes: parseInt(e.target.value) || 0 } })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm" /></div></div><div><label className="text-sm font-medium">{t("lockoutPolicy.captchaTrigger")}</label><input type="number" value={data.config.captcha_trigger_attempts} onChange={(e) => setData({ ...data, config: { ...data.config, captcha_trigger_attempts: parseInt(e.target.value) || 0 } })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm" /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.config.progressive_backoff} onChange={(e) => setData({ ...data, config: { ...data.config, progressive_backoff: e.target.checked } })} className="rounded" /> {t("lockoutPolicy.progressiveBackoff")}</label></div>
        <div className="rounded-lg border dark:border-gray-800 p-4"><h3 className="text-sm font-semibold mb-2">{t("lockoutPolicy.perEndpoint")}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-3 py-2 text-left font-medium">{t("bruteForce.endpoint")}</th><th className="px-3 py-2 text-left font-medium">{t("bruteForce.maxAttempts")}</th><th className="px-3 py-2 text-left font-medium">{t("lockoutPolicy.lockoutDuration")}</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{data.config.per_endpoint.map((ep, i) => (<tr key={i} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-3 py-2 font-mono text-xs">{ep.endpoint}</td><td className="px-3 py-2"><input aria-label="ep" type="number" value={ep.max_attempts} onChange={(e) => { const pe = [...data.config.per_endpoint]; pe[i] = { ...ep, max_attempts: parseInt(e.target.value) || 0 }; setData({ ...data, config: { ...data.config, per_endpoint: pe } }); }} className="w-16 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs" /></td><td className="px-3 py-2"><input type="number" value={ep.duration_minutes} onChange={(e) => { const pe = [...data.config.per_endpoint]; pe[i] = { ...ep, duration_minutes: parseInt(e.target.value) || 0 }; setData({ ...data, config: { ...data.config, per_endpoint: pe } }); }} className="w-16 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs" /></td></tr>))}</tbody></table></div></div>
        <div className="rounded-lg border dark:border-gray-800 p-4"><h3 className="text-sm font-semibold mb-2">{t("lockoutPolicy.ipAllowlist")}</h3><div className="flex flex-wrap gap-1">{data.config.ip_allowlist.map((ip) => <span key={ip} className="px-2 py-0.5 rounded text-xs bg-green-100 dark:bg-green-900/30 dark:text-green-400 font-mono">{ip}</span>)}{data.config.ip_allowlist.length === 0 && <span className="text-xs text-gray-400">None</span>}</div></div>
        {data.active_lockouts.length > 0 && <div className="rounded-lg border border-red-300 dark:border-red-800 p-4"><div className="flex items-center gap-2 mb-2"><Shield className="w-4 h-4 text-red-500" /><h3 className="text-sm font-semibold text-red-700 dark:text-red-400">{t("lockoutPolicy.activeLockouts")} ({data.active_lockouts.length})</h3></div><div className="space-y-1">{data.active_lockouts.map((l, i) => (<div key={i} className="text-xs flex items-center gap-2"><span className="font-medium">{l.username}</span><span className="text-gray-400">{l.ip}</span><span className="text-gray-400 ml-auto">unlock: {l.unlock_at}</span></div>))}</div></div>}
      </>)}
      {!data && !loading && <p className="text-sm text-gray-500 text-center py-8">{t("common.loading")}</p>}
    </div>
  );
}
