"use client";
import { useState, useEffect, useCallback } from "react";
import { Server, Plug, RefreshCw, CheckCircle, XCircle } from "lucide-react";
interface LdapConfig { server_url: string; bind_dn: string; base_dn: string; user_filter: string; group_filter: string; start_tls: boolean; attribute_mapping: { ldap_attr: string; local_attr: string }[]; sync_schedule: string; last_sync: string | null; auto_provision: boolean; }
export default function LdapSyncConfigPage() {
  const [config, setConfig] = useState<LdapConfig>({ server_url: "", bind_dn: "", base_dn: "", user_filter: "(objectClass=person)", group_filter: "(objectClass=groupOfNames)", start_tls: true, attribute_mapping: [{ ldap_attr: "uid", local_attr: "username" }, { ldap_attr: "mail", local_attr: "email" }, { ldap_attr: "cn", local_attr: "display_name" }], sync_schedule: "0 */6 * * *", last_sync: null, auto_provision: true });
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<boolean | null>(null);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const loadData = useCallback(async () => {
    setLoading(true); setError(null);
    try { const res = await fetch("/api/v1/auth/ldap-config", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) { const d = await res.json(); if (d) setConfig(prev => ({ ...prev, ...d })); } }
    catch (err: any) { setError(err.message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { loadData(); }, [loadData]);
  const save = async () => { setSaving(true); try { await fetch("/api/v1/auth/ldap-config", { method: "PUT", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(config) }); } catch { /* noop */ } finally { setSaving(false); } };
  const test = async () => { setTesting(true); setTestResult(null); try { const res = await fetch("/api/v1/auth/ldap-config/test", { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(config) }); setTestResult(res.ok); } catch { setTestResult(false); } finally { setTesting(false); } };
  if (loading) return (<div className="p-8 flex items-center justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" /></div>);
  if (error) return (<div className="p-8"><div className="rounded-lg border border-red-300 bg-red-50 dark:bg-red-950 dark:border-red-800 p-4"><p className="text-red-700 dark:text-red-400 text-sm font-medium">Error: {error}</p><button onClick={loadData} className="mt-2 px-4 py-1.5 rounded-lg bg-red-600 text-white text-sm hover:bg-red-700">Retry</button></div></div>);
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Server className="w-6 h-6 text-blue-500" /> LDAP Sync Config</h1><p className="text-sm text-gray-500 mt-1">Configure LDAP server connection and sync settings.</p></div><div className="flex gap-2"><button onClick={test} disabled={testing} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm font-medium flex items-center gap-2"><Plug className={"w-4 h-4 " + (testing ? "animate-pulse" : "")} /> {testing ? "Testing..." : "Test Connection"}</button><button onClick={save} disabled={saving} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium">{saving ? "Saving..." : "Save"}</button></div></div>
      {testResult !== null && <div className={"rounded-lg border p-3 flex items-center gap-2 " + (testResult ? "border-green-300 dark:border-green-800 bg-green-50 dark:bg-green-900/20" : "border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-900/20")}>{testResult ? <CheckCircle className="w-5 h-5 text-green-500" /> : <XCircle className="w-5 h-5 text-red-500" />}<span className={"text-sm font-medium " + (testResult ? "text-green-700 dark:text-green-400" : "text-red-700 dark:text-red-400")}>{testResult ? "Connection successful" : "Connection failed"}</span></div>}
      <div className="rounded-lg border dark:border-gray-800 p-4 space-y-3 max-w-lg"><div className="grid grid-cols-1 gap-3"><div><label className="text-sm font-medium">Server URL</label><input type="text" value={config.server_url} onChange={(e) => setConfig({ ...config, server_url: e.target.value })} placeholder="ldap://dc01.example.com:389" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div><div><label className="text-sm font-medium">Bind DN</label><input type="text" value={config.bind_dn} onChange={(e) => setConfig({ ...config, bind_dn: e.target.value })} placeholder="cn=admin,dc=example,dc=com" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div><div><label className="text-sm font-medium">Base DN</label><input type="text" value={config.base_dn} onChange={(e) => setConfig({ ...config, base_dn: e.target.value })} placeholder="dc=example,dc=com" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div><div><label className="text-sm font-medium">User Filter</label><input type="text" value={config.user_filter} onChange={(e) => setConfig({ ...config, user_filter: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div><div><label className="text-sm font-medium">Group Filter</label><input type="text" value={config.group_filter} onChange={(e) => setConfig({ ...config, group_filter: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div><div className="flex items-center gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.start_tls} onChange={(e) => setConfig({ ...config, start_tls: e.target.checked })} className="rounded" /> Start TLS</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.auto_provision} onChange={(e) => setConfig({ ...config, auto_provision: e.target.checked })} className="rounded" /> Auto Provision</label></div></div></div>
      <div className="rounded-lg border dark:border-gray-800 p-4"><h3 className="text-sm font-semibold mb-2">Attribute Mapping</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-3 py-2 text-left font-medium">LDAP Attribute</th><th className="px-3 py-2 text-left font-medium">Local Attribute</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{config.attribute_mapping.map((m, i) => (<tr key={i} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-3 py-2"><input type="text" value={m.ldap_attr} onChange={(e) => { const a = [...config.attribute_mapping]; a[i] = { ...m, ldap_attr: e.target.value }; setConfig({ ...config, attribute_mapping: a }); }} className="w-full px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></td><td className="px-3 py-2"><input type="text" value={m.local_attr} onChange={(e) => { const a = [...config.attribute_mapping]; a[i] = { ...m, local_attr: e.target.value }; setConfig({ ...config, attribute_mapping: a }); }} className="w-full px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></td></tr>))}</tbody></table></div></div>
      <div className="rounded-lg border dark:border-gray-800 p-4 flex items-center gap-3"><div><label className="text-sm font-medium">Sync Schedule (Cron)</label><input type="text" value={config.sync_schedule} onChange={(e) => setConfig({ ...config, sync_schedule: e.target.value })} className="mt-1 px-3 py-1.5 rounded border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div>{config.last_sync && <div><span className="text-xs text-gray-500">Last Sync</span><p className="text-xs text-gray-400">{config.last_sync}</p></div>}</div>
    </div>
  );
}
