"use client";
import { useState, useEffect, useCallback } from "react";
import { Database, Plus, X, Save } from "lucide-react";
import { useTranslations } from "@/lib/i18n";
interface RetentionRule { event_type: string; retention_days: number; action: "archive" | "delete" | "anonymize"; compliance_basis: string; }
interface RetentionData { rules: RetentionRule[]; storage_used_gb: number; storage_limit_gb: number; per_tenant: boolean; purge_schedule: string; }
const actions = ["archive", "delete", "anonymize"];
const actionColors: Record<string, string> = { archive: "bg-blue-100 dark:bg-blue-900/30 dark:text-blue-400", delete: "bg-red-100 dark:bg-red-900/30 dark:text-red-400", anonymize: "bg-yellow-100 dark:bg-yellow-900/30 dark:text-yellow-400" };
export default function AuditRetentionPolicyPage() {
  const t = useTranslations();
  const [data, setData] = useState<RetentionData | null>(null);
  const [loading, setLoading] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState<{ event_type: string; retention_days: number; action: "archive" | "delete" | "anonymize"; compliance_basis: string }>({ event_type: "", retention_days: 365, action: "archive", compliance_basis: "" });
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/audit/retention-policy", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) setData(await res.json()); } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const addRule = () => { if (!form.event_type || !data) return; setData({ ...data, rules: [...data.rules, { ...form }] }); setShowAdd(false); setForm({ event_type: "", retention_days: 365, action: "archive", compliance_basis: "" }); };
  const removeRule = (i: number) => { if (!data) return; setData({ ...data, rules: data.rules.filter((_, idx) => idx !== i) }); };
  const save = async () => { if (!data) return; try { await fetch("/api/v1/audit/retention-policy", { method: "PUT", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(data) }); } catch { /* noop */ } };
  const storagePct = data ? Math.round((data.storage_used_gb / data.storage_limit_gb) * 100) : 0;
  const storageColor = storagePct > 80 ? "#ef4444" : storagePct > 60 ? "#f59e0b" : "#10b981";
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Database className="w-6 h-6 text-blue-500" />{t("auditRetentionPolicy.title")}</h1><p className="text-sm text-gray-500 mt-1">{t("auditRetention.subtitle")}</p></div><div className="flex gap-2"><button onClick={() => setShowAdd(true)} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4" /> {t("auditRetention.addRule")}</button><button onClick={save} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm font-medium flex items-center gap-2" aria-label="Save"><Save className="w-4 h-4" /> {t("common.save")}</button></div></div>
      {data && (<>
        <div className="flex items-center gap-4"><div className="relative w-20 h-20"><svg viewBox="0 0 64 64" className="w-full h-full"><circle cx={32} cy={32} r={28} fill="none" stroke="currentColor" strokeWidth={6} className="text-gray-200 dark:text-gray-800" /><circle cx={32} cy={32} r={28} fill="none" stroke={storageColor} strokeWidth={6} strokeDasharray={(storagePct / 100) * 176 + " 176"} strokeLinecap="round" transform="rotate(-90 32 32)" /></svg><div className="absolute inset-0 flex items-center justify-center"><span className="text-sm font-bold" style={{ color: storageColor }}>{storagePct}%</span></div></div><div><span className="text-sm text-gray-500">{t("auditRetention.storageUsed")}</span><p className="text-lg font-bold">{data.storage_used_gb.toFixed(1)} / {data.storage_limit_gb} GB</p></div><div className="ml-4"><span className="text-sm text-gray-500">{t("auditRetention.purgeSchedule")}</span><p className="text-sm font-mono">{data.purge_schedule}</p></div><label className="flex items-center gap-2 text-sm ml-4"><input aria-label="Data" type="checkbox" checked={data.per_tenant} onChange={(e) => setData({ ...data, per_tenant: e.target.checked })} className="rounded" /> {t("auditRetention.perTenant")}</label></div>
        <div className="overflow-x-auto rounded-lg border dark:border-gray-800"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-4 py-3 text-left font-medium">Event Type</th><th className="px-4 py-3 text-left font-medium">Retention (days)</th><th className="px-4 py-3 text-left font-medium">Action</th><th className="px-4 py-3 text-left font-medium">Compliance Basis</th><th className="px-4 py-3 text-left font-medium"></th></tr></thead><tbody className="divide-y dark:divide-gray-800">{data.rules.map((r, i) => (<tr key={i} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-4 py-3 font-mono text-xs font-medium">{r.event_type}</td><td className="px-4 py-3"><input aria-label="r" type="number" value={r.retention_days} onChange={(e) => { const rules = [...data.rules]; rules[i] = { ...r, retention_days: parseInt(e.target.value) || 0 }; setData({ ...data, rules }); }} className="w-20 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs" /></td><td className="px-4 py-3"><select value={r.action} onChange={(e) => { const rules = [...data.rules]; rules[i] = { ...r, action: e.target.value as RetentionRule["action"] }; setData({ ...data, rules }); }} className={"px-2 py-0.5 rounded text-xs " + actionColors[r.action]}><option value="archive">Archive</option><option value="delete">Delete</option><option value="anonymize">Anonymize</option></select></td><td className="px-4 py-3 text-xs text-gray-500">{r.compliance_basis || "-"}</td><td className="px-4 py-3"><button onClick={() => removeRule(i)} className="text-red-500"><X className="w-3.5 h-3.5" /></button></td></tr>))}{data.rules.length === 0 && <tr><td colSpan={5} className="px-4 py-8 text-center text-gray-500">No retention rules.</td></tr>}</tbody></table></div>
      </>)}
      {showAdd && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowAdd(false)}><div role="dialog" aria-modal="true" className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b dark:border-gray-800"><h3 className="font-semibold">Add Retention Rule</h3><button onClick={() => setShowAdd(false)} aria-label="Close"><X className="w-5 h-5 text-gray-400" /></button></div><div className="px-6 py-4 space-y-3"><div><label className="text-sm font-medium">Event Type</label><input type="text" value={form.event_type} onChange={(e) => setForm({ ...form, event_type: e.target.value })} placeholder="auth.login" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">Retention (days)</label><input type="number" value={form.retention_days} onChange={(e) => setForm({ ...form, retention_days: parseInt(e.target.value) || 0 })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Action</label><select value={form.action} onChange={(e) => setForm({ ...form, action: e.target.value as "archive" | "delete" | "anonymize" })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm">{actions.map((a) => <option key={a} value={a}>{a}</option>)}</select></div><div><label className="text-sm font-medium">Compliance Basis</label><input type="text" value={form.compliance_basis} onChange={(e) => setForm({ ...form, compliance_basis: e.target.value })} placeholder="GDPR Art. 5" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t dark:border-gray-800"><button onClick={() => setShowAdd(false)} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm">Cancel</button><button onClick={addRule} disabled={!form.event_type} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium disabled:opacity-50">Add</button></div></div></div>)}
      {!data && !loading && <p className="text-sm text-gray-500 text-center py-8">{t("common.loading")}</p>}
    </div>
  );
}
