apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ggidinstances.iam.ggid.dev
spec:
  group: iam.ggid.dev
  names:
    kind: GGIDInstance
    listKind: GGIDInstanceList
    plural: ggidinstances
    singular: ggidinstance
    shortNames:
      - ggi
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - tier
                - organizationName
                - database
                - adminEmail
              properties:
                tier:
                  type: string
                  default: dedicated
                organizationName:
                  type: string
                namespace:
                  type: string
                replicas:
                  type: integer
                  default: 2
                database:
                  type: object
                  required: [driver, host]
                  properties:
                    driver:
                      type: string
                      default: postgres
                    host:
                      type: string
                    port:
                      type: integer
                      default: 5432
                    name:
                      type: string
                      default: ggid
                    sslMode:
                      type: string
                      default: require
                adminEmail:
                  type: string
                idpConfig:
                  type: object
                  properties:
                    provider:
                      type: string
                    entityId:
                      type: string
                    ssoUrl:
                      type: string
                    certificate:
                      type: string
                helmChartRef:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                namespace:
                  type: string
                helmRelease:
                  type: string
                tenantId:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
