"use client";
import { useState, useEffect, useCallback } from "react";
import { Palette, Upload, Eye, Save } from "lucide-react";
interface Branding { logo_url: string; primary_color: string; secondary_color: string; accent_color: string; custom_css: string; theme: "light" | "dark" | "auto"; custom_domain: string; }
export default function TenantBrandingPage() {
  const [branding, setBranding] = useState<Branding>({ logo_url: "", primary_color: "#3b82f6", secondary_color: "#1e40af", accent_color: "#f59e0b", custom_css: "", theme: "auto", custom_domain: "" });
  const [saving, setSaving] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const save = async () => { setSaving(true); try { await fetch("/api/v1/admin/branding", { method: "PUT", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify(branding) }); } catch { /* noop */ } finally { setSaving(false); } };
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Palette className="w-6 h-6 text-purple-500" /> Tenant Branding</h1><p className="text-sm text-gray-500 mt-1">Customize logo, colors, and domain for your tenant.</p></div><button onClick={save} disabled={saving} className="px-4 py-2 rounded-lg bg-purple-600 text-white text-sm font-medium flex items-center gap-2"><Save className="w-4 h-4" /> {saving ? "Saving..." : "Save"}</button></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div className="rounded-lg border dark:border-gray-800 p-4"><label className="text-sm font-medium">Logo</label><div className="mt-2 flex items-center gap-3"><div className="w-20 h-20 rounded-lg border-2 border-dashed dark:border-gray-700 flex items-center justify-center overflow-hidden">{branding.logo_url ? <img src={branding.logo_url} alt="logo" className="w-full h-full object-contain" /> : <Upload className="w-6 h-6 text-gray-400" />}</div><input type="text" value={branding.logo_url} onChange={(e) => setBranding({ ...branding, logo_url: e.target.value })} placeholder="https://.../logo.png" className="flex-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div></div>
          <div className="rounded-lg border dark:border-gray-800 p-4"><h3 className="text-sm font-semibold mb-3">Colors</h3><div className="grid grid-cols-3 gap-3"><div><label className="text-xs text-gray-500">Primary</label><div className="flex items-center gap-2 mt-1"><input type="color" value={branding.primary_color} onChange={(e) => setBranding({ ...branding, primary_color: e.target.value })} className="w-8 h-8 rounded" /><input type="text" value={branding.primary_color} onChange={(e) => setBranding({ ...branding, primary_color: e.target.value })} className="w-20 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></div></div><div><label className="text-xs text-gray-500">Secondary</label><div className="flex items-center gap-2 mt-1"><input type="color" value={branding.secondary_color} onChange={(e) => setBranding({ ...branding, secondary_color: e.target.value })} className="w-8 h-8 rounded" /><input type="text" value={branding.secondary_color} onChange={(e) => setBranding({ ...branding, secondary_color: e.target.value })} className="w-20 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></div></div><div><label className="text-xs text-gray-500">Accent</label><div className="flex items-center gap-2 mt-1"><input type="color" value={branding.accent_color} onChange={(e) => setBranding({ ...branding, accent_color: e.target.value })} className="w-8 h-8 rounded" /><input type="text" value={branding.accent_color} onChange={(e) => setBranding({ ...branding, accent_color: e.target.value })} className="w-20 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></div></div></div></div>
          <div className="rounded-lg border dark:border-gray-800 p-4"><label className="text-sm font-medium">Theme</label><select value={branding.theme} onChange={(e) => setBranding({ ...branding, theme: e.target.value as Branding["theme"] })} className="ml-3 px-3 py-1.5 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm"><option value="light">Light</option><option value="dark">Dark</option><option value="auto">Auto</option></select></div>
          <div className="rounded-lg border dark:border-gray-800 p-4"><label className="text-sm font-medium">Custom Domain</label><input type="text" value={branding.custom_domain} onChange={(e) => setBranding({ ...branding, custom_domain: e.target.value })} placeholder="login.example.com" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-sm font-mono" /></div>
          <div className="rounded-lg border dark:border-gray-800 p-4"><label className="text-sm font-medium">Custom CSS</label><textarea value={branding.custom_css} onChange={(e) => setBranding({ ...branding, custom_css: e.target.value })} rows={6} placeholder="/* .login-btn { border-radius: 8px; } */" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-900 text-xs font-mono" /></div>
        </div>
        <div><div className="flex items-center justify-between mb-2"><h3 className="text-sm font-semibold">Login Page Preview</h3><button onClick={() => setShowPreview(!showPreview)} className="text-xs flex items-center gap-1 text-gray-500"><Eye className="w-3.5 h-3.5" /> Toggle</button></div>{showPreview && <div className="rounded-lg border dark:border-gray-800 p-8" style={{ background: branding.theme === "dark" ? "#1a1a1a" : "#f8fafc" }}><div className="max-w-sm mx-auto rounded-lg shadow-lg p-6" style={{ background: branding.theme === "dark" ? "#222" : "#fff" }}>{branding.logo_url && <img src={branding.logo_url} alt="logo" className="h-12 mx-auto mb-4" />}<h2 className="text-center text-lg font-bold mb-4" style={{ color: branding.primary_color }}>Sign In</h2><input type="text" placeholder="Email" className="w-full px-3 py-2 rounded-lg border dark:border-gray-700 mb-2 text-sm" style={{ borderColor: branding.secondary_color }} /><input type="password" placeholder="Password" className="w-full px-3 py-2 rounded-lg border dark:border-gray-700 mb-4 text-sm" style={{ borderColor: branding.secondary_color }} /><button className="w-full py-2 rounded-lg text-white text-sm font-medium" style={{ background: branding.primary_color }}>Sign In</button><style>{branding.custom_css}</style></div></div>}</div>
      </div>
    </div>
  );
}
