package router

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

// TestFullChain_HealthCheckPasses verifies that public health endpoint
// goes through the full middleware chain and returns 200.
func TestFullChain_HealthCheckPasses(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200 for /healthz, got %d", rr.Code)
	}
}

// TestFullChain_ProtectedPathReturns401 verifies that a protected path
// without JWT returns 401 through the full chain.
func TestFullChain_ProtectedPathReturns401(t *testing.T) {
	backend := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer backend.Close()

	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/api/v1/users", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401 without JWT, got %d", rr.Code)
	}
}

// TestFullChain_MetricsAccessible verifies /metrics is exposed.
func TestFullChain_MetricsAccessible(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/metrics", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200 for /metrics, got %d", rr.Code)
	}
}

// TestFullChain_DeepHealthAccessible verifies /healthz/deep is exposed.
func TestFullChain_DeepHealthAccessible(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz/deep", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	// 200 (no backends = ok) or 503 (no backends = degraded)
	if rr.Code != http.StatusOK && rr.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected 200 or 503 for /healthz/deep, got %d", rr.Code)
	}
}

// TestFullChain_RequestIDAutoGenerated verifies the chain generates X-Request-ID.
func TestFullChain_RequestIDAutoGenerated(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Header().Get("X-Request-ID") == "" {
		t.Fatal("expected auto-generated X-Request-ID")
	}
}

// TestFullChain_RequestIDPreserved verifies incoming X-Request-ID is forwarded.
func TestFullChain_RequestIDPreserved(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	req.Header.Set("X-Request-ID", "trace-abc-123")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if got := rr.Header().Get("X-Request-ID"); got != "trace-abc-123" {
		t.Fatalf("expected X-Request-ID 'trace-abc-123', got %q", got)
	}
}
