package router

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestRequestID_AutoGenerated(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	rid := rr.Header().Get("X-Request-ID")
	if rid == "" {
		t.Fatal("expected auto-generated X-Request-ID")
	}
}

func TestRequestID_PreservedFromIncoming(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	req.Header.Set("X-Request-ID", "incoming-trace-999")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if got := rr.Header().Get("X-Request-ID"); got != "incoming-trace-999" {
		t.Fatalf("expected 'incoming-trace-999', got %q", got)
	}
}

func TestRequestID_UniquePerRequest(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req1 := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr1 := httptest.NewRecorder()
	handler.ServeHTTP(rr1, req1)

	req2 := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr2 := httptest.NewRecorder()
	handler.ServeHTTP(rr2, req2)

	if rr1.Header().Get("X-Request-ID") == rr2.Header().Get("X-Request-ID") {
		t.Fatal("expected different request IDs for two requests")
	}
}
