package router

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

// TestRequestID_AutoGenerated verifies that a request without X-Request-ID
// gets one generated and set in the response header.
func TestRequestID_AutoGenerated(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	// No X-Request-ID header set
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	rid := rr.Header().Get("X-Request-ID")
	if rid == "" {
		t.Fatal("expected auto-generated X-Request-ID in response header")
	}
}

// TestRequestID_PreservedFromIncoming verifies that an incoming X-Request-ID
// is preserved and forwarded in the response.
func TestRequestID_PreservedFromIncoming(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	req.Header.Set("X-Request-ID", "my-trace-id-12345")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	rid := rr.Header().Get("X-Request-ID")
	if rid != "my-trace-id-12345" {
		t.Fatalf("expected X-Request-ID 'my-trace-id-12345', got %q", rid)
	}
}

// TestRequestID_UniquePerRequest verifies that two sequential requests
// get different X-Request-ID values.
func TestRequestID_UniquePerRequest(t *testing.T) {
	gw := newTestGateway(t)
	handler := gw.Handler()

	req1 := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr1 := httptest.NewRecorder()
	handler.ServeHTTP(rr1, req1)
	rid1 := rr1.Header().Get("X-Request-ID")

	req2 := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rr2 := httptest.NewRecorder()
	handler.ServeHTTP(rr2, req2)
	rid2 := rr2.Header().Get("X-Request-ID")

	if rid1 == rid2 {
		t.Fatalf("expected different request IDs, got %q twice", rid1)
	}
}
