"use client";
import { useState, useEffect, useCallback } from "react";
import { Smartphone, ShieldCheck, AlertTriangle } from "lucide-react";
import { useTranslations } from "@/lib/i18n";
import { authHeader, isAuthenticated } from "@/lib/auth-helpers";
interface PostureRule { disk_encrypted: boolean; os_version_min: string; antivirus_required: boolean; firewall_enabled: boolean; jailbreak_detected_action: string; }
interface NonCompliant { device_id: string; username: string; platform: string; failed_checks: string[]; last_check: string; }
interface PostureData { rules: PostureRule; compliance_threshold: number; by_platform: { platform: string; total: number; compliant: number }[]; non_compliant: NonCompliant[]; }
export default function DevicePosturePage() {
  const t = useTranslations();

  const [data, setData] = useState<PostureData | null>(null);
  const [loading, setLoading] = useState(false);
  const [tab, setTab] = useState("all");
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/identity/device-posture", { headers: { ...authHeader(), "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) setData(await res.json()); } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const filtered = data ? (tab === "all" ? data.non_compliant : data.non_compliant.filter((d: any) => d.platform === tab)) : [];
  return (
    <div className="space-y-6">
      <div><h1 className="text-2xl font-bold flex items-center gap-2"><Smartphone className="w-6 h-6 text-blue-500" /> {t("big1.devicePosture.title")}</h1><p className="text-sm text-gray-500 mt-1">{t("big1.devicePosture.enforceDeviceSecurityPostureRequirements")}</p></div>
      {data && (<>
        <div className="rounded-lg border dark:border-gray-800 p-4 space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">{t("big1.devicePosture.postureRules")}</h3><div className="flex items-center gap-2"><span className="text-xs text-gray-500">{t("big1.devicePosture.complianceThreshold")}</span><input type="number" min={0} max={100} defaultValue={data.compliance_threshold} className="w-16 px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs" /><span className="text-xs">%</span></div></div><div className="grid grid-cols-2 md:grid-cols-3 gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={data.rules.disk_encrypted} className="rounded" />{t("big1.devicePosture.diskEncrypted")}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={data.rules.antivirus_required} className="rounded" />{t("big1.devicePosture.antivirusRequired")}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={data.rules.firewall_enabled} className="rounded" />{t("big1.devicePosture.firewallEnabled")}</label><div><label className="text-xs text-gray-500">{t("big1.devicePosture.minOsVersion")}</label><input type="text" defaultValue={data.rules.os_version_min} className="w-full px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs" /></div><div><label className="text-xs text-gray-500">{t("big1.devicePosture.jailbreakAction")}</label><select aria-label="Select option" defaultValue={data.rules.jailbreak_detected_action} className="w-full px-2 py-1 rounded border dark:border-gray-700 dark:bg-gray-900 text-xs"><option value="block">{t("big1.devicePosture.block")}</option><option value="warn">{t("big1.devicePosture.warn")}</option></select></div></div></div>
        <div className="grid grid-cols-3 gap-4">{data.by_platform.map((p: any) => { const pct = p.total > 0 ? Math.round((p.compliant / p.total) * 100) : 100; return (<div key={p.platform} className="rounded-lg border p-4 dark:border-gray-800"><span className="text-sm text-gray-500 capitalize">{p.platform}</span><p className={"text-xl font-bold mt-1 " + (pct >= 90 ? "text-green-600" : pct >= 70 ? "text-yellow-600" : "text-red-600")}>{pct}%</p><p className="text-xs text-gray-400">{p.compliant}/{p.total}{t("big1.devicePosture.compliant")}</p></div>); })}</div>
        <div className="flex gap-2"><button onClick={() => setTab("all")} aria-label="Show all platforms" className={"px-3 py-1.5 rounded-lg text-xs font-medium " + (tab === "all" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>{t("big1.devicePosture.all")}</button><button onClick={() => setTab("ios")} aria-label="Show iOS only" className={"px-3 py-1.5 rounded-lg text-xs font-medium " + (tab === "ios" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>{t("big1.devicePosture.ios")}</button><button onClick={() => setTab("android")} aria-label="Show Android only" className={"px-3 py-1.5 rounded-lg text-xs font-medium " + (tab === "android" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>{t("big1.devicePosture.android")}</button><button onClick={() => setTab("windows")} aria-label="Show Windows only" className={"px-3 py-1.5 rounded-lg text-xs font-medium " + (tab === "windows" ? "bg-blue-600 text-white" : "border dark:border-gray-700")}>{t("big1.devicePosture.windows")}</button></div>
        <div className="overflow-x-auto rounded-lg border dark:border-gray-800"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-4 py-3 text-left font-medium">{t("big1.devicePosture.device")}</th><th className="px-4 py-3 text-left font-medium">{t("big1.devicePosture.user")}</th><th className="px-4 py-3 text-left font-medium">{t("big1.devicePosture.failedChecks")}</th><th className="px-4 py-3 text-left font-medium">{t("big1.devicePosture.lastCheck")}</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{filtered.map((d: any) => (<tr key={d.device_id} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-4 py-3 font-mono text-xs">{d.device_id}</td><td className="px-4 py-3">{d.username}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{d.failed_checks.map((c: any) => <span key={c} className="px-1.5 py-0.5 rounded text-xs bg-red-100 dark:bg-red-900/30 dark:text-red-400">{c}</span>)}</div></td><td className="px-4 py-3 text-xs text-gray-400">{d.last_check}</td></tr>))}{filtered.length === 0 && <tr><td colSpan={4} className="px-4 py-8 text-center text-gray-500">{t("big1.devicePosture.noNonCompliantDevices")}</td></tr>}</tbody></table></div>
      </>)}
      {!data && !loading && <p className="text-sm text-gray-500 text-center py-8">{t("big1.devicePosture.loading")}</p>}
    </div>
  );
}
