"use client";
import { useState, useEffect, useCallback } from "react";
import { Key, Plus, X, RotateCcw, Ban } from "lucide-react";
interface ApiKey { id: string; name: string; scopes: string[]; created_at: string; expires_at: string; last_used: string | null; status: "active" | "expired" | "revoked"; usage_count: number; }
const statusColors: Record<string, string> = { active: "bg-green-100 dark:bg-green-900/30 dark:text-green-400", expired: "bg-gray-100 dark:bg-gray-800 dark:text-gray-400", revoked: "bg-red-100 dark:bg-red-900/30 dark:text-red-400" };
export default function APIKeyLifecyclePage() {
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [loading, setLoading] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: "", scopes: "", expires_at: "" });
  const fetchData = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/v1/auth/api-keys", { headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); if (res.ok) { const d = await res.json(); setKeys(d.keys || d || []); } } catch { /* noop */ } finally { setLoading(false); } }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const create = async () => { if (!form.name) return; try { await fetch("/api/v1/auth/api-keys", { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" }, body: JSON.stringify({ name: form.name, scopes: form.scopes.split(",").map((s) => s.trim()).filter(Boolean), expires_at: form.expires_at }) }); setShowCreate(false); setForm({ name: "", scopes: "", expires_at: "" }); fetchData(); } catch { /* noop */ } };
  const rotate = async (id: string) => { try { await fetch("/api/v1/auth/api-keys/" + id + "/rotate", { method: "POST", headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); fetchData(); } catch { /* noop */ } };
  const revoke = async (id: string) => { try { await fetch("/api/v1/auth/api-keys/" + id, { method: "DELETE", headers: { "X-Tenant-ID": "00000000-0000-0000-0000-000000000001" } }); fetchData(); } catch { /* noop */ } };
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Key className="w-6 h-6 text-blue-500" /> API Key Lifecycle</h1><p className="text-sm text-gray-500 mt-1">Manage API keys: create, rotate, revoke.</p></div><button onClick={() => setShowCreate(true)} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4" /> Create Key</button></div>
      <div className="overflow-x-auto rounded-lg border dark:border-gray-800"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-900/50"><tr><th className="px-4 py-3 text-left font-medium">Name</th><th className="px-4 py-3 text-left font-medium">Scopes</th><th className="px-4 py-3 text-left font-medium">Created</th><th className="px-4 py-3 text-left font-medium">Expires</th><th className="px-4 py-3 text-left font-medium">Last Used</th><th className="px-4 py-3 text-left font-medium">Usage</th><th className="px-4 py-3 text-left font-medium">Status</th><th className="px-4 py-3 text-left font-medium">Actions</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{keys.map((k) => (<tr key={k.id} className="hover:bg-gray-50 dark:hover:bg-gray-900/30"><td className="px-4 py-3 font-medium">{k.name}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1 max-w-32">{k.scopes.map((s) => <span key={s} className="px-1 py-0.5 rounded text-xs bg-gray-100 dark:bg-gray-800 font-mono">{s}</span>)}</div></td><td className="px-4 py-3 text-xs text-gray-500">{k.created_at}</td><td className="px-4 py-3 text-xs text-gray-500">{k.expires_at}</td><td className="px-4 py-3 text-xs text-gray-500">{k.last_used || "-"}</td><td className="px-4 py-3 text-xs font-bold">{k.usage_count.toLocaleString()}</td><td className="px-4 py-3"><span className={"px-2 py-0.5 rounded text-xs " + statusColors[k.status]}>{k.status}</span></td><td className="px-4 py-3"><div className="flex gap-2">{k.status === "active" && <><button onClick={() => rotate(k.id)} className="text-xs text-blue-600 hover:underline flex items-center gap-1"><RotateCcw className="w-3 h-3" /> Rotate</button><button onClick={() => revoke(k.id)} className="text-xs text-red-600 hover:underline flex items-center gap-1"><Ban className="w-3 h-3" /> Revoke</button></>}</div></td></tr>))}{keys.length === 0 && !loading && <tr><td colSpan={8} className="px-4 py-8 text-center text-gray-500">No API keys.</td></tr>}</tbody></table></div>
      {showCreate && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowCreate(false)}><div className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b dark:border-gray-800"><h3 className="font-semibold">Create API Key</h3><button onClick={() => setShowCreate(false)}><X className="w-5 h-5 text-gray-400" /></button></div><div className="px-6 py-4 space-y-3"><div><label className="text-sm font-medium">Name</label><input type="text" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div><div><label className="text-sm font-medium">Scopes (comma-separated)</label><input type="text" value={form.scopes} onChange={(e) => setForm({ ...form, scopes: e.target.value })} placeholder="read:users, write:roles" className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm font-mono" /></div><div><label className="text-sm font-medium">Expires At</label><input type="date" value={form.expires_at} onChange={(e) => setForm({ ...form, expires_at: e.target.value })} className="w-full mt-1 px-3 py-2 rounded-lg border dark:border-gray-700 dark:bg-gray-800 text-sm" /></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t dark:border-gray-800"><button onClick={() => setShowCreate(false)} className="px-4 py-2 rounded-lg border dark:border-gray-700 text-sm">Cancel</button><button onClick={create} disabled={!form.name} className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium disabled:opacity-50">Create</button></div></div></div>)}
    </div>
  );
}
